Object storage test
IBM-Swift/generator-swiftserver pull request #184
Opened 2017-05-02 12:15 UTC by tunniclm

2017-05-03 09:44 UTC, rob-deans requested changes

2017-05-03 09:44 UTC, rob-deans commented on test/integration/app/spec_build.js
> +      appType: 'web',
`appType` is now only `scaffold` or `crud` might want to change that plus update the others

2017-05-03 09:44 UTC, rob-deans commented on test/integration/app/spec_build.js
> +      appType: 'web',
Adding `web: true` would make it web app

2017-05-05 12:25 UTC, tunniclm commented on test/integration/app/spec_build.js
> +      appType: 'web',
OK, I'm going to add checking into the refresh generator to validate the value of `appType`. I will do this in a separate PR, check the incorrect tests fail, then fix them.

2017-05-06 08:53 UTC, tunniclm commented on test/integration/app/spec_build.js
> +      appType: 'web',
The latest commits should address all of these points, please can you review again. Thanks

2017-05-08 08:38 UTC, rob-deans approved these changes

2017-05-08 10:10 UTC, merged