Watson conversation
IBM-Swift/generator-swiftserver pull request #205
Opened 2017-05-13 19:12 UTC by jkingoliver

fyi https://github.com/IBM-Swift/CloudConfiguration/pull/25

2017-05-15 09:23 UTC, tunniclm commented
Changed to be targeted against `develop`.

2017-05-15 09:35 UTC, tunniclm requested changes
This good work, just a couple of things I'd like to see either discussed / changed. If you disagree with any of the comments, I'd love to hear the reasons and discuss. Thanks :)

2017-05-15 09:35 UTC, tunniclm commented on refresh/templates/services/watsonconversation/initializeBluemixService.swift
> +
Can this code be compressed? In other services we have used an extension of the client object to handle creation directly from the service returned by the ConfigurationManager.

2017-05-15 09:35 UTC, tunniclm commented on refresh/templates/services/watsonconversation/importDependency.swift
> +        .Package(url: "https://github.com/watson-developer-cloud/swift-sdk",    majorVersion: 0),
For dependencies with major version at `0`, I like to specify the minor as well. Whilst there are no rules for `0` versions (the are counted as "in development"), often projects will update the minor on breaking changes.

There is also the question of whether anything should really be a `0` release if other projects are depending on it.

2017-05-16 09:14 UTC, tunniclm reviewed
Look like you will need to rebase this branch before we can merge.

2017-05-16 17:36 UTC, jkingoliver commented on refresh/templates/services/watsonconversation/importDependency.swift
> +        .Package(url: "https://github.com/watson-developer-cloud/swift-sdk",    majorVersion: 0),
As we discussed in scrum, we will address questions with how to represent dependency versions at our next sprint planning meeting

2017-05-16 17:36 UTC, jkingoliver commented on refresh/templates/services/watsonconversation/initializeBluemixService.swift
> +
I extracted the initialization code to the Extension file and removed the sample code.

2017-05-17 16:10 UTC, tunniclm approved these changes

2017-05-17 16:53 UTC, merged